Fix build error from unused kThreadNetworkName variable. (#5126)
Compiler says:
  error: unused variable 'kThreadNetworkName' [-Werror,-Wunused-const-variable]