Also add dependency from Darwin platform to avoid:
```
g++ -MMD -MF
obj/third_party/connectedhomeip/src/platform/Darwin/Darwin.PosixConfig.cpp.o.d
-target x86_64-apple-macos10.15 -O0 -g2 -fno-common -ffunction-sections
-fdata-sections -fno-exceptions -fno-unwind-tables
-fno-asynchronous-unwind-tables -fPIC -Wall -Werror -Wextra -Wshadow
-Wunreachable-code -Wvla -Wno-deprecated-declarations
-Wno-unknown-warning-option -Wno-maybe-uninitialized
-Wno-missing-field-initializers -Wno-unused-parameter -Wno-psabi
-Wno-cast-function-type -fdiagnostics-color -fno-strict-aliasing
-fsanitize=thread -fobjc-arc
-I/usr/local/Cellar/openssl@1.1/1.1.1l_1/include -std=gnu++14 -fno-rtti
-Wnon-virtual-dtor -DCHIP_HAVE_CONFIG_H=1
-I../../../examples/all-clusters-app/linux/third_party/connectedhomeip/src/include
-I../../../examples/all-clusters-app/linux/third_party/connectedhomeip/src
-Igen/include
-I../../../examples/all-clusters-app/linux/third_party/connectedhomeip/zzz_generated/app-common
-I../../../examples/all-clusters-app/linux/third_party/connectedhomeip/config/standalone
-I../../../examples/all-clusters-app/linux/third_party/connectedhomeip/third_party/nlassert/repo/include
-I../../../examples/all-clusters-app/linux/third_party/connectedhomeip/third_party/nlio/repo/include
-c
../../../examples/all-clusters-app/linux/third_party/connectedhomeip/src/platform/Darwin/PosixConfig.cpp
-o
obj/third_party/connectedhomeip/src/platform/Darwin/Darwin.PosixConfig.cpp.o
245
In file included from
../../../examples/all-clusters-app/linux/third_party/connectedhomeip/src/platform/Darwin/PosixConfig.cpp:27:
246
In file included from
../../../examples/all-clusters-app/linux/third_party/connectedhomeip/src/include/platform/internal/CHIPDeviceLayerInternal.h:22:
247
In file included from
../../../examples/all-clusters-app/linux/third_party/connectedhomeip/src/include/platform/CHIPDeviceLayer.h:29:
248
In file included from
../../../examples/all-clusters-app/linux/third_party/connectedhomeip/src/include/platform/ConnectivityManager.h:27:
249
In file included from
../../../examples/all-clusters-app/linux/third_party/connectedhomeip/src/app/AttributeAccessInterface.h:22:
250
In file included from
../../../examples/all-clusters-app/linux/third_party/connectedhomeip/src/app/MessageDef/AttributeDataElement.h:26:
251
../../../examples/all-clusters-app/linux/third_party/connectedhomeip/src/app/MessageDef/AttributePath.h:29:10:
fatal error: 'app/AppBuildConfig.h' file not found
252
```