Fix warnings -Warray-bounds & disabled -Wunused
OpenThread EFR32 platform has many instances of variables only used by
assert(), which is a no-op in release builds. Pass -Wno-ununused in
these builds to avoid the warning.

Also, add a trailing NULL to emAfEventStrings to avoid a warning from
-Warray-bounds:

../../src/app/util/af-event.cpp: In function 'const char* emberAfGetEventString(uint8_t)':
../../src/app/util/af-event.cpp:103:74: error: array subscript 0 is above array bounds of 'const char* [0]' [-Werror=array-bounds]
  103 |     return (index == 0XFF ? emAfStackEventString : emAfEventStrings[index]);
      |                                                    ~~~~~~~~~~~~~~~~~~~~~~^