[python tests] decode shell output as UTF-8 (#26783)
If tests are run on a platform which is returning special characters
(e.g. date with months which contain an umlaut) runnig the test fails:

```
  File "/home/sag/projects/project-chip/connectedhomeip/./scripts/tests/run_python_test.py", line 95, in main
    print(subprocess.check_output(["ls -l"], shell=True).decode('us-ascii'))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1553: ordinal not in range(128)
```

Decode the output using UTF-8 by default.