silabs/zephyr: fix CMSIS dependency
Currently, the compilation may fail with:

    In file included from .../zephyr/arch/arm/asm_inline.h:18,
                     from .../zephyr/arch/arm/arch.h:30,
                     from .../zephyr/arch/cpu.h:19,
                     from .../zephyr/kernel_includes.h:36,
                     from .../zephyr/kernel.h:17,
                     from .../matter/src/system/SystemMutex.h:60,
                     from .../matter/src/system/SystemMutex.cpp:26:
    .../zephyr/arch/arm/asm_inline_gcc.h:24:10: fatal error: cmsis_core.h: No such file or directory
       24 | #include <cmsis_core.h>
          |          ^~~~~~~~~~~~~~
    compilation terminated.

By specifying cmsis_6 and mbedtls explicitly, we guarantee their
CMakeLists.txt will be included first. Thus,
INTERFACE_INCLUDE_DIRECTORIES is properly filled when Matter
CMakelists.txt is included.

Signed-off-by: Jérôme Pouiller <jerome.pouiller@silabs.com>