Fix EFR32 VSCode build
As of 281eceadb1 ("[EFR32] RAM Optimization (#5646)") there is
an error linking EFR32 examples in VS Code:

 ld:  obj/third_party/connectedhomeip/third_party/efr32_sdk/repo/util/third_party/freertos/Source/sdk.event_groups.c.o: in function `xEventGroupCreate':
/workspaces/connectedhomeip-vscode/out/efr32_lighting_app/../../examples/lighting-app/efr32/third_party/connectedhomeip/third_party/efr32_sdk/repo/util/third_party/freertos/Source/event_groups.c:175: undefined reference to `pvPortMalloc'
 ld:  obj/third_party/connectedhomeip/third_party/efr32_sdk/repo/util/third_party/freertos/Source/sdk.queue.c.o: in function `xQueueGenericCreate':
/workspaces/connectedhomeip-vscode/out/efr32_lighting_app/../../examples/lighting-app/efr32/third_party/connectedhomeip/third_party/efr32_sdk/repo/util/third_party/freertos/Source/queue.c:403: undefined reference to `pvPortMalloc'
 ld:  obj/third_party/connectedhomeip/third_party/efr32_sdk/repo/util/third_party/freertos/Source/sdk.queue.c.o: in function `vQueueDelete':
/workspaces/connectedhomeip-vscode/out/efr32_lighting_app/../../examples/lighting-app/efr32/third_party/connectedhomeip/third_party/efr32_sdk/repo/util/third_party/freertos/Source/queue.c:2013: undefined reference to `vPortFree'
 ld:  obj/third_party/connectedhomeip/third_party/efr32_sdk/repo/util/third_party/freertos/Source/sdk.tasks.c.o: in function `prvDeleteTCB':
/workspaces/connectedhomeip-vscode/out/efr32_lighting_app/../../examples/lighting-app/efr32/third_party/connectedhomeip/third_party/efr32_sdk/repo/util/third_party/freertos/Source/tasks.c:3933: undefined reference to `vPortFree'
 ld:  /workspaces/connectedhomeip-vscode/out/efr32_lighting_app/../../examples/lighting-app/efr32/third_party/connectedhomeip/third_party/efr32_sdk/repo/util/third_party/freertos/Source/tasks.c:3934: undefined reference to `vPortFree'
 ld:  /workspaces/connectedhomeip-vscode/out/efr32_lighting_app/../../examples/lighting-app/efr32/third_party/connectedhomeip/third_party/efr32_sdk/repo/util/third_party/freertos/Source/tasks.c:3940: undefined reference to `vPortFree'
 ld:  obj/third_party/connectedhomeip/third_party/efr32_sdk/repo/util/third_party/freertos/Source/sdk.timers.c.o: in function `xTimerCreate':
/workspaces/connectedhomeip-vscode/out/efr32_lighting_app/../../examples/lighting-app/efr32/third_party/connectedhomeip/third_party/efr32_sdk/repo/util/third_party/freertos/Source/timers.c:303: undefined reference to `pvPortMalloc'
 ld:  obj/third_party/connectedhomeip/third_party/efr32_sdk/repo/util/third_party/freertos/Source/sdk.timers.c.o: in function `prvProcessReceivedCommands':
/workspaces/connectedhomeip-vscode/out/efr32_lighting_app/../../examples/lighting-app/efr32/third_party/connectedhomeip/third_party/efr32_sdk/repo/util/third_party/freertos/Source/timers.c:868: undefined reference to `vPortFree'
collect2: error: ld returned 1 exit status

This happens because there are now important options set in
gn_efr32_example.sh. Move them to src/platform/EFR32/args.gni
so they apply without having to use this script.