Fix wrong uint64_t print
Problem:
Regression issue
Problem
../../src/app/tests/integration/chip_im_initiator.cpp:86:68: error: format specifies type 'unsigned long' but the argument has type 'chip::NodeId' (aka 'unsigned long long') [-Werror,-Wformat]

Summary of changes

Always use PRIu64 for printing uint64_t, including node ids.

Fixes #4284