Empty out af-gen-event.h for thermostat sample
This application does not enable the door lock or barrier control
clusters. Remove the corresponding event code.

This code caused linker errors in some configurations (ASAN):

  g++ -O0 -fPIC -Werror -Wl,--fatal-warnings -fdiagnostics-color -fsanitize=address -fno-omit-frame-pointer -Wl,--gc-sections -pie -Wl,-Map,standalone/thermostat-app.map @standalone/thermostat-app.rsp -o standalone/thermostat-app
  /usr/bin/ld: standalone/obj/src/app/util/thermostat-common.af-event.cpp.o: in function `emberAfBarrierControlClusterServerTickCallbackWrapperFunction1()':
  /ssd/src/connectedhomeip/out/debug/../../src/app/util/af-event.cpp:69: undefined reference to `emberAfBarrierControlClusterServerTickCallback(unsigned short)'