[linux] fix header order; fix build
After the latest rebase, the following error was coming up:

```
../../src/include/platform/ConnectivityManager.h:252:40: fatal error: platform/CHIP_DEVICE_LAYER_TARGET/ConnectivityManagerImpl.h: No such file or directory
  252 | #define CONNECTIVITYMANAGERIMPL_HEADER <platform/CHIP_DEVICE_LAYER_TARGET/ConnectivityManagerImpl.h>
```

Though CHIP_DEVICE_LAYER_TARGET=Linux is set using AC_SUBST in configure.ac,
the definition, which was working fine before, was mysteriously getting lost.
It turns out the header re-ordering PR was the root cause of the issue.

The fix was to change all sources in src/platform/Linux to
move this include first:
    #include <platform/internal/CHIPDeviceLayerInternal.h>

The error did not lead to the fix in an obvious way, so the issue
is being documented here.