ESP32: Remove esp32_mbedtls component(v1.1 cherry-pick of PR 26608 and PR 26750) (#26779)
* ESP32: use mbedtls config in IDF

* esp32: remove esp32_mbedtls component

* Add CONFIG_MBEDTLS_HKDF_C=y to some esp32 defaults. (#26750)

This seems to be required, otherwise I get errors like:

```
config/esp32/third_party/connectedhomeip/src/crypto/CHIPCryptoPALmbedTLS.cpp:330: undefined reference to `mbedtls_hkdf'
```

Co-authored-by: Andrei Litvin <andreilitvin@google.com>

* Remove 'CONFIG_MBEDTLS_HKDF_C=y' for sdkconfig.defaults.<target-name> files

---------

Co-authored-by: Andrei Litvin <andy314@gmail.com>
Co-authored-by: Andrei Litvin <andreilitvin@google.com>