[crypto] Fix compile error in BufferWriter init
BufferWriter class expects a (uint8_t*, size_t) as initialization.
The given parameter 'output' was a `P256SerializedKeypair` which throws a compiler error.

Output: used compiler - gcc-arm-none-eabi-9-2019-q4-major
In member function 'virtual CHIP_ERROR chip::Crypto::P256Keypair::Serialize(chip::Crypto::P256SerializedKeypair&) const':
.../src/crypto/CHIPCryptoPALPSA.cpp:685:51: error: no matching function for call to 'chip::Encoding::BufferWriter::BufferWriter(chip::Crypto::P256SerializedKeypair&, const size_t&)'
  685 |     Encoding::BufferWriter bbuf(output, outputSize);

Fix:
Use the `Bytes` method to expose a uint8_t* for use of the BufferWriter.