Add missing include <inttypes.h> (#5233)
This fixes a compile error with certain stdlibs:

app/server/Mdns.cpp:57:69: error: expected ')'
        ChipLogProgress(Discovery, "Found admin paring for admin %" PRIX64 ", node %" PRIX64, pairing->GetAdminId(),