[silabs] Fix 917 support (Auto-merged by platform-bot)
* silabs/zephyr: fix Kconfig indentation

Apply the same rules than the Zephyr and the Linux projects:
  - Indent with tab
  - Indent help with tab + 2 spaces
  - Limit on 80 columns (In fact, 84 columns because Matter uses 4
    spaces for a tab)
  - No indentation inside choice/if statements
  - No trailing spaces

* silabs/zephyr: fix promptless symbol

Silicon Labs Kconfigs provide default values for plenty of options.
However, if the type of the symbol is provided, the symbol is a new
instance, which is generally not the intention.

This patch is specifically fixing BT_HOST_CRYPTO because Gemini is
complaining about it. However, this change should be applied to the
others symbols.

Signed-off-by: Jérôme Pouiller <jerome.pouiller@silabs.com>

* silabs/zephyr: fix DeviceInfoProvider initialization order

Server::Init() triggers various callbacks (e.g. attribute reads, fabric
enumeration) that can call DeviceLayer::GetDeviceInfoProvider(). If
gExampleDeviceInfoProvider is registered *after* Server::Init() returns,
those callbacks silently get a NULL provider and fail to retrieve device
info (product name, vendor ID, etc.), leading to incorrect behaviour
during commissioning.

Fix by moving the SetStorageDelegate() / SetDeviceInfoProvider() calls to
before Server::Init(), using initParams.persistentStorageDelegate directly
(which is the same object that Server::GetPersistentStorage() would
return afterwards).

Also guard the OperationalKeystore::Init() call under
CONFIG_OPERATIONAL_KEYSTORE since persistentStorage is only needed in
that context.

Co-authored-by: Copilot <223556219+Copilot@users.noreply.github.com>

* silabs/zephyr: update overlays for siwx917

ulpuart and sram was already configured with the configuration in
Zephyr. So these entries were useless.

In addition, the offset of the storage_partition overlapped with
ota_swap_partition. So the OTA process would probably overwrite the
data. The available flash ends at 0x00400000.

So, we slightly reduced the size of the code_partition to allocate the
storage_partition at the end of the available area:

  0x00400000 -- end --
  0x003e9000 storage
  0x003e1000 settings
  0x003e0000 factory
  0x00202000 code

This patch also align the size of the storage partitions on brd4338 and
brd4342 (was 68kB, updated to 92kB).

Signed-off-by: Jérôme Pouiller <jerome.pouiller@silabs.com>

* silabs/zephyr: fix PSA_CRYPTO_SW_ONLY dependency

Currently, Zephyr compilation fails with:

    warning: default on the choice symbol PSA_CRYPTO_SW_ONLY will have
    no effect, as defaults do not affect choice symbols

Indeed PSA_CRYPTO_SW_ONLY should be selected either with

    choice PSA_CRYPTO_DRIVER_IMPLEMENTATION
           default PSA_CRYPTO_SW_ONLY
    endchoice

or with:

    depends on PSA_CRYPTO_SW_ONLY

BTW, since v2026.06 PSA_CRYPTO_SW_ONLY is the default for swix91x. So
this statement can be removed.

Signed-off-by: Jérôme Pouiller <jerome.pouiller@silabs.com>

* silabs/zephyr: fix CMSIS dependency

Currently, the compilation may fail with:

    In file included from .../zephyr/arch/arm/asm_inline.h:18,
                     from .../zephyr/arch/arm/arch.h:30,
                     from .../zephyr/arch/cpu.h:19,
                     from .../zephyr/kernel_includes.h:36,
                     from .../zephyr/kernel.h:17,
                     from .../matter/src/system/SystemMutex.h:60,
                     from .../matter/src/system/SystemMutex.cpp:26:
    .../zephyr/arch/arm/asm_inline_gcc.h:24:10: fatal error: cmsis_core.h: No such file or directory
       24 | #include <cmsis_core.h>
          |          ^~~~~~~~~~~~~~
    compilation terminated.

By specifying cmsis_6 and mbedtls explicitly, we guarantee their
CMakeLists.txt will be included first. Thus,
INTERFACE_INCLUDE_DIRECTORIES is properly filled when Matter
CMakelists.txt is included.

Signed-off-by: Jérôme Pouiller <jerome.pouiller@silabs.com>

* silabs/zephyr: fix support for WiFi

During my tests, the commissioning failed without
CONFIG_CHIP_ENABLE_WIFI_STATION=y.

In addition, the "select" statement only select the specified symbol
without taking the dependencies into account. It is better to reverse
the dependency (CHIP_WIFI is default y but depends on WIFI).

Signed-off-by: Jérôme Pouiller <jerome.pouiller@silabs.com>

* silabs/zephyr: relocate POSIX_AEP_CHOICE_NONE

POSIX_AEP_CHOICE_NONE is global to the whole Matter project, is not
specific to the lighting sample. So, relocate the option.

Signed-off-by: Jérôme Pouiller <jerome.pouiller@silabs.com>

* silabs/zephyr: drop useless USE_SEGGER_RTT=n

Many board in Matter explicitly disable USE_SEGGER_RTT=n. It seems it is
because these board enable RTT by default in their _defconfig. Silabs
board don't do that (the user has to explicitly reference
rtt-console/rtt-console.conf snippet).

So, the current USE_SEGGER_RTT=n is either useless or error prone for
the user who really want to use RTT.

Signed-off-by: Jérôme Pouiller <jerome.pouiller@silabs.com>

* silabs/zephyr: drop explicit dependency on TLS

CONFIG_THREAD_LOCAL_STORAGE=y is already the default in Zephyr. Explicit
selection in prj.conf does not seem useful.

The origin of this setting maybe related to CONFIG_SLOW_FLASH_DATA
(which is suggested for siwx91x). Help of SILABS_SIWX91X_SLOW_FLASH_DATA
says:

    With current GCC versions (14.x), this option is incompatible with
    Thread Local Storage (TLS). User may either:
      - Use a patched version of gcc (preferred option), or
      - Rebuild libc (CONFIG_PICOLIBC_USE_MODULE=y) without TLS support
        (CONFIG_THREAD_LOCAL_STORAGE=n). In this case, access to
        "errno" will no longer be thread-safe.

Signed-off-by: Jérôme Pouiller <jerome.pouiller@silabs.com>

* silabs/zephyr: drop useless dependency on UART_ASYNC_API

Lighting application does not seems to rely on UART async API. BTW,
siwx91x does not support this API. So, CONFIG_UART_ASYNC_API=y seems to
be a mistake.

Signed-off-by: Jérôme Pouiller <jerome.pouiller@silabs.com>

* silabs/zephyr: drop useless dependency on SECURE_STORAGE_..._AES_GCM

SECURE_STORAGE_ITS_TRANSFORM_AEAD_SCHEME_AES_GCM is already the default
in Zephyr.

(BTW, SECURE_STORAGE_ITS_TRANSFORM_AEAD_SCHEME_CHACHA20_POLY1305 is
probably a faster alternative)

Signed-off-by: Jérôme Pouiller <jerome.pouiller@silabs.com>

* silabs/zephyr: group Kconfig options

Order Kconfig options:
  1. Subsystems. Because of "depends on", many options are automatically
     selected with these options.
  2. Application related options
  3. Shell commands. It makes sense to easily add remove shell commands
     during the development
  4. Stack sizes. It makes sense to group them since the user often has
     to tune them.
  5. Debug and temporary options (empty in this sample)

Signed-off-by: Jérôme Pouiller <jerome.pouiller@silabs.com>

* silabs/zephyr: drop debug features

lighting-app/silabs/zephyr/prj.conf contain a bunch of option related to
the log and the shell threads. These option are probably not required
for the sample. The defaults parameters should be sufficient and we
don't expect to see a such level of details in a sample project.

Signed-off-by: Jérôme Pouiller <jerome.pouiller@silabs.com>

---------

Signed-off-by: Jérôme Pouiller <jerome.pouiller@silabs.com>
Co-authored-by: Copilot <223556219+Copilot@users.noreply.github.com>
Co-authored-by: Jean-Francois Penven <67962328+jepenven-silabs@users.noreply.github.com>