Upgrade labeler config to v5 from v4 (#31024)
* Update labeler.yaml

* Update labeler.yml -> Updating config file to solve for the error after the merge

Error Link: https://github.com/project-chip/connectedhomeip/actions/runs/7213100260/job/19652200726?pr=31009

Error: found unexpected type for label 'scripts' (should be array of config options)

* Update labeler.yaml -> Changing workflow to the major version v5 instead of v5.0.0

Changing workflow to the major version v5 instead of v5.0.0