Fix build warning on Android in CHIPCryptoPALOpenSSL.cpp
X509_VERIFY_PARAM_set_time takes in time_t as the unix epoch parameter.
On Android this is defined as a 'long', so need to cast the value to
suppress the warning.

src/crypto/CHIPCryptoPALOpenSSL.cpp:1672:43: error: implicit conversion changes signedness: 'uint32_t' (aka 'unsigned int') to 'time_t' (aka 'long') [-Werror,-Wsign-conversion]
        X509_VERIFY_PARAM_set_time(param, unixEpoch);