Support building chip-tool with python3.12 (#33242) (#33770)
This updates 2 python packages to versions compatible with python3.12,
fixing the following errors when running
`./scripts/examples/gn_build_example.sh examples/chip-tool BUILDFOLDER`:

1. `pyyaml` 6.0 build error: `AttributeError: cython_sources`, fixed
   [here](https://github.com/yaml/pyyaml/pull/702)
2. `construct` import error:

   ```
           File "/tmp/pip-install-ifgk4tul/construct_6d60304f85e249759f6c184ea89f1317/construct/core.py", line 3, in <module>
          import struct, io, binascii, itertools, collections, pickle, sys, os, tempfile, hashlib, importlib, imp
      ModuleNotFoundError: No module named 'imp'
   ```

   this was fixed
   [here](https://github.com/construct/construct/commit/91cc0c65f5f8ceace2ee59da5068da92519a99c9),
   in version `v2.10.57` of `construct`. I'm just
   updating to latest though.

Now running `./scripts/examples/gn_build_example.sh examples/chip-tool
BUILDFOLDER` succeeds when the host python is python3.12.

Co-authored-by: Noah Pendleton <2538614+noahp@users.noreply.github.com>