Implement GroupCast Test Cases (#42143)
* begin implementation gcast 2.1, 2.2, 2.3

* draft implementation of ot TC_GCAST_2_1 and TC_GCAST_2_3

* fix typo in retrieve_join_group_cmd_endpoints

* add GCAST_2_4 and GCAST_2_5 implementation, update GCAST_2_3

* add GCAST_2_6 implementation, update get endpoints list in other GCAST test cases

* add GCAST_2_6, missed in previous commit

* add GCAST_2_7 and update other GCAST test cases to use secrets lib for keys

* minor fixes pr copilot comments

* add missing step for TC_GCAST_2_5 and fix TC_GCAST_2_1 syntax error

* fix GCAST_2_6 and GCAST_2_7 imports and test names

* address most comments by Junior and copilot

* address comments by tcarmelveilleux

* fix test name in GCAST_2_6

* move common logic to TC_GCAST_common, update test cases and update based on comments

* WIP boilerplate for TC_GCAST_2_2

* Finished first pass of TC_GCAST_2_2; will come back to clean up comments

* fixed catching exceptions

* Adding step description above each step as a comment to help reader follow tests in-line.

* Addressing rest of comments from @tcarmelveilleux

* Revert commits by @PriyaMalhotra3 on wrong branch

* Fix linter

- Fix copyright dates
- Fix the following lints:

```
Error: src/python_testing/TC_GCAST_2_1.py:40:38: F401 `matter.interaction_model.Status` imported but unused
Error: src/python_testing/TC_GCAST_2_1.py:41:69: F401 `matter.testing.matter_testing.async_test_body` imported but unused
Error: src/python_testing/TC_GCAST_2_1.py:57:16: RET504 Unnecessary assignment to `pics` before `return` statement
Error: src/python_testing/TC_GCAST_2_3.py:43:43: F401 `matter.testing.matter_testing.AttributeMatcher` imported but unused
Error: src/python_testing/TC_GCAST_2_3.py:43:87: F401 `matter.testing.matter_testing.async_test_body` imported but unused
Error: src/python_testing/TC_GCAST_2_3.py:77:16: RET504 Unnecessary assignment to `pics` before `return` statement
Error: src/python_testing/TC_GCAST_2_3.py:154:9: ASYNC251 Async functions should not call `time.sleep`
Error: src/python_testing/TC_GCAST_2_4.py:43:69: F401 `matter.testing.matter_testing.async_test_body` imported but unused
Error: src/python_testing/TC_GCAST_2_4.py:71:16: RET504 Unnecessary assignment to `pics` before `return` statement
Error: src/python_testing/TC_GCAST_2_5.py:43:69: F401 `matter.testing.matter_testing.async_test_body` imported but unused
Error: src/python_testing/TC_GCAST_2_5.py:80:16: RET504 Unnecessary assignment to `pics` before `return` statement
Error: src/python_testing/TC_GCAST_2_6.py:43:69: F401 `matter.testing.matter_testing.async_test_body` imported but unused
Error: src/python_testing/TC_GCAST_2_6.py:72:16: RET504 Unnecessary assignment to `pics` before `return` statement
Error: src/python_testing/TC_GCAST_2_7.py:41:69: F401 `matter.testing.matter_testing.async_test_body` imported but unused
Error: src/python_testing/TC_GCAST_2_7.py:66:16: RET504 Unnecessary assignment to `pics` before `return` statement
Error: src/python_testing/TC_GCAST_common.py:53:17: RET507 Unnecessary `else` after `continue` statement
Error: src/python_testing/TC_GCAST_common.py:152:86: W292 No newline at end of file
```

* Restyled by autopep8

* Restyled by isort

* fix imports, resolve comments

* fix ci arguments block, fix typo in GCAST_common

* fix TC_GCAST_common imports in TC_GCAST test cases, and add test cases to test_metadata.yaml to prevent from running in CI for now

* update reason for TC_GCAST in test_metatadata.yaml, remove set endpoint blocks in TC_GCAST test cases

* Restyled by prettier-yaml

* Restyled by isort

---------

Co-authored-by: Priya Malhotra <priyamal@google.com>
Co-authored-by: tennessee.carmelveilleux@gmail.com <tennessee.carmelveilleux@gmail.com>
Co-authored-by: Restyled.io <commits@restyled.io>