[python] fix platform specific wheel to be spec compliant
The current build approach causes bdist_wheel to store the shared library
in the purelib folder. However, a platform specific wheel should have
shared libraries in the platform specific folder, not in the purelib folder.

This has been discovered using `auditwheel check`:

```
RuntimeError: Invalid binary wheel, found the following shared library/libraries in purelib folder:
        _ChipDeviceCtrl.so
The wheel has to be platlib compliant in order to be repaired by auditwheel.
```

This makes the wheel pass `auditwheel check`.