Add nicer logging for InteractionModel::Status.
After this change we get things like:

    Error: IM Error 0x000005C6: General error: 0xc6 (NEEDS_TIMED_INTERACTION)

instead of just

    Error: IM Error 0x000005C6: General error: 0xc6