Rename OpenThread configs to new names
Fixes the following errors:

error: #error "OPENTHREAD_CONFIG_MAX_TX_ATTEMPTS_INDIRECT_POLLS was
replaced by OPENTHREAD_CONFIG_MAC_MAX_TX_ATTEMPTS_INDIRECT_POLLS."
  223 | #error \
      |  ^~~~~

etc.