Fix build error from unused kThreadNetworkName variable.
Compiler says:
  error: unused variable 'kThreadNetworkName' [-Werror,-Wunused-const-variable]